# Generated by Django 5.1.5 on 2025-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
    ]
